spring:
  application:
    name: board # 앱 이름
  security: # ID, PW
    user:
      name: u
      password: u
  main:
    allow-bean-definition-overriding: false # bean설정 중복허용 여부 true를 하면 마지막 중복된 bean이 최종적으로 덮어져서 사용됨
  #개발툴 옵션 관리
  devtools:
    restart:
      enabled: false #실행중 개발코드 변경 감지시 자동 재시작 기능 활성화 여부
      additional-paths: classpath:/
    livereload:
      enabled: true #브라우저에서 자동변경 감지 리로드
  thymeleaf:
    cache: false #타임리프 템플릿 캐시 유지여부, 개발중에는 비활성화가 반영이 더 빠름
  # HTML FORM은 PUT DELETE가 없음 따라서 Hidden Method 활성화하는 옵션 사용방법은 th:method=
  mvc:
    hidden-method:
      filter:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  #JPA
  jpa:
    show-sql: false #true는 Log에 sql내역 디버깅
    hibernate:
      # DDL (Data Definition Language) 설정
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # SQL 쿼리를 포맷팅하여 보기 쉽게 만듭니다.
    generate-ddl: true  # true로 설정하면 JPA가 데이터베이스 스키마를 생성하거나 업데이트합니다. 일반적으로 false로 설정합니다.
    database: mysql
    # database-platform: org.hibernate.dialect.MariaDB103Dialect
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${common.global-ip}:3306/HAM_DB
    username:
    password:
  # h2:
  #  console:
  #    enabled: true
  #    path: /h2
  #    settings:
  #      web-allow-others: true
  #      trace: false
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

common:
  local-ip: localhost
  global-ip: 158.180.87.21
